# Generated by Django 4.1 on 2022-09-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('computer_type', models.CharField(max_length=100)),
                ('modal_No', models.CharField(max_length=100)),
                ('computer_series', models.CharField(max_length=100)),
                ('computer_ram', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberXapp.computer')),
            ],
        ),
    ]
