# Generated by Django 4.1 on 2022-09-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberXapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
